# Generated by Django 3.2.5 on 2022-01-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20220109_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='natijalar',
            old_name='Test',
            new_name='Test1',
        ),
    ]
