# Generated by Django 3.2.5 on 2022-01-09 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_test_natijalar_test1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natijalar',
            name='Test1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.testmodul'),
        ),
    ]
